# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.CharField(default=1, max_length=66),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.CharField(default=1, max_length=66),
            preserve_default=False,
        ),
    ]
