# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfolio', '0004_auto_20180816_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('css', 'css'), ('html5', 'htm'), ('flask', 'flask'), ('geodjango', 'geodjango'), ('angularjs', 'angularjs'), ('postgresql', 'postgresql')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
